<?php

namespace Biuio\Meter\dlt645;

use Biuio\Meter\dlt645;
use Biuio\Meter\lib\tool;

/**
 * 表A.4 事件记录数据标识编码表
 */
class di3_03 extends di3
{
    const DIs = [
        "ABC相失压总次数，总累计时间" => [
            "03", "01", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "A相失压总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "B相失压总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "C相失压总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "A相失压记录" => [ //最近10次
            "03", "01", "01", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "失压期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "失压期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失压期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失压期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "失压期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "失压期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失压期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失压期间A相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "失压期间A相电压"],
                ["XXX.XXX", 3, "A", "double", "失压期间A相电流"],
                ["XX.XXXX", 3, "kW", "double", "失压期间A相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "失压期间A相无功功率"],
                ["X.XXX", 2, "", "double", "失压期间A相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "失压期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "失压期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失压期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失压期间B相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "失压期间B相电压"],
                ["XXX.XXX", 3, "A", "double", "失压期间B相电流"],
                ["XX.XXXX", 3, "kW", "double", "失压期间B相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "失压期间B相无功功率"],
                ["X.XXX", 2, "", "double", "失压期间B相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "失压期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "失压期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失压期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失压期间C相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "失压期间C相电压"],
                ["XXX.XXX", 3, "A", "double", "失压期间C相电流"],
                ["XX.XXXX", 3, "kW", "double", "失压期间C相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "失压期间C相无功功率"],
                ["X.XXX", 2, "", "double", "失压期间C相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "Ah", "double", "失压期间总安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "失压期间A相安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "失压期间B相安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "失压期间C相安时数"],
            ],
            "r",
            "最近10次"
        ],
        "B相失压记录" => ["03", "01", "02", "01", "引用[A相失压记录]格式", "r", "最近10次"], //最近10次
        "C相失压记录" => ["03", "01", "03", "01", "引用[A相失压记录]格式", "r", "最近10次"], //最近10次
        //"---",
        "ABC相欠压总次数，总累计时间" => [
            "03", "02", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "A相欠压总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "B相欠压总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "C相欠压总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "A相欠压记录" => [ //最近10次
            "03", "02", "01", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "欠压期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "欠压期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "欠压期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "欠压期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "欠压期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "欠压期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "欠压期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "欠压期间A相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "欠压期间A相电压"],
                ["XXX.XXX", 3, "A", "double", "欠压期间A相电流"],
                ["XX.XXXX", 3, "kW", "double", "欠压期间A相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "欠压期间A相无功功率"],
                ["X.XXX", 2, "", "double", "欠压期间A相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "欠压期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "欠压期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "欠压期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "欠压期间B相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "欠压期间B相电压"],
                ["XXX.XXX", 3, "A", "double", "欠压期间B相电流"],
                ["XX.XXXX", 3, "kW", "double", "欠压期间B相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "欠压期间B相无功功率"],
                ["X.XXX", 2, "", "double", "欠压期间B相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "欠压期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "欠压期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "欠压期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "欠压期间C相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "欠压期间C相电压"],
                ["XXX.XXX", 3, "A", "double", "欠压期间C相电流"],
                ["XX.XXXX", 3, "kW", "double", "欠压期间C相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "欠压期间C相无功功率"],
                ["X.XXX", 2, "", "double", "欠压期间C相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "Ah", "double", "欠压期间总安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "欠压期间A相安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "欠压期间B相安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "欠压期间C相安时数"],
            ],
            "r",
            "最近10次"
        ],
        "B相欠压记录" => ["03", "02", "02", "01", "引用[A相欠压记录]格式", "r", "最近10次"], //最近10次
        "C相欠压记录" => ["03", "02", "03", "01", "引用[A相欠压记录]格式", "r", "最近10次"], //最近10次
        //"---",
        "ABC相过压总次数，总累计时间" => [
            "03", "03", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "A相过压总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "B相过压总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "C相过压总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "A相过压记录" => [ //最近10次
            "03", "03", "01", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "过压期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过压期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过压期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过压期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "过压期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过压期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过压期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过压期间A相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "过压期间A相电压"],
                ["XXX.XXX", 3, "A", "double", "过压期间A相电流"],
                ["XX.XXXX", 3, "kW", "double", "过压期间A相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "过压期间A相无功功率"],
                ["X.XXX", 2, "", "double", "过压期间A相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "过压期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过压期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过压期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过压期间B相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "过压期间B相电压"],
                ["XXX.XXX", 3, "A", "double", "过压期间B相电流"],
                ["XX.XXXX", 3, "kW", "double", "过压期间B相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "过压期间B相无功功率"],
                ["X.XXX", 2, "", "double", "过压期间B相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "过压期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过压期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过压期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过压期间C相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "过压期间C相电压"],
                ["XXX.XXX", 3, "A", "double", "过压期间C相电流"],
                ["XX.XXXX", 3, "kW", "double", "过压期间C相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "过压期间C相无功功率"],
                ["X.XXX", 2, "", "double", "过压期间C相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "Ah", "double", "过压期间总安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "过压期间A相安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "过压期间B相安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "过压期间C相安时数"],
            ],
            "r",
            "最近10次"
        ],
        "B相过压记录" => ["03", "03", "02", "01", "引用[A相过压记录]格式", "r", "最近10次"], //最近10次
        "C相过压记录" => ["03", "03", "03", "01", "引用[A相过压记录]格式", "r", "最近10次"], //最近10次
        //"---",
        "ABC相断相总次数，总累计时间" => [
            "03", "04", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "A相断相总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "B相断相总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "C相断相总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "A相断相记录" => [ //最近10次
            "03", "04", "01", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "断相期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "断相期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断相期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断相期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "断相期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "断相期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断相期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断相期间A相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "断相期间A相电压"],
                ["XXX.XXX", 3, "A", "double", "断相期间A相电流"],
                ["XX.XXXX", 3, "kW", "double", "断相期间A相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "断相期间A相无功功率"],
                ["X.XXX", 2, "", "double", "断相期间A相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "断相期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "断相期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断相期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断相期间B相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "断相期间B相电压"],
                ["XXX.XXX", 3, "A", "double", "断相期间B相电流"],
                ["XX.XXXX", 3, "kW", "double", "断相期间B相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "断相期间B相无功功率"],
                ["X.XXX", 2, "", "double", "断相期间B相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "断相期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "断相期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断相期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断相期间C相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "断相期间C相电压"],
                ["XXX.XXX", 3, "A", "double", "断相期间C相电流"],
                ["XX.XXXX", 3, "kW", "double", "断相期间C相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "断相期间C相无功功率"],
                ["X.XXX", 2, "", "double", "断相期间C相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "Ah", "double", "断相期间总安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "断相期间A相安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "断相期间B相安时数"],
                ["XXXXXX.XX", 4, "Ah", "double", "断相期间C相安时数"],
            ],
            "r",
            "最近10次"
        ],
        "B相断相记录" => ["03", "04", "02", "01", "引用[A相断相记录]格式", "r", "最近10次"], //最近10次
        "C相断相记录" => ["03", "04", "03", "01", "引用[A相断相记录]格式", "r", "最近10次"], //最近10次
        //"---",
        "全失压总次数，总累计时间" => [
            "03", "05", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "全失压总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "全失压发生时刻，电流值，结束时刻" => [ //最近10次
            "03", "05", "00", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "全失压发生时刻"],
                ["XXX.XXX", 3, "A", "double", "电流值"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "结束时刻"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "辅助电源失电总次数，总累计时间" => [
            "03", "06", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "辅助电源失电总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "辅助电源失电发生时刻，结束时刻" => [ //最近10次
            "03", "06", "00", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "辅助电源失电发生时刻"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "结束时刻"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "电压逆相序总次数，总累计时间" => [
            "03", "07", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "电压逆相序总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "电压逆相序记录" => [ //最近10次
            "03", "07", "00", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "电压逆相序期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电压逆相序期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压逆相序期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压逆相序期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电压逆相序期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电压逆相序期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压逆相序期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压逆相序期间A相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电压逆相序期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电压逆相序期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压逆相序期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压逆相序期间B相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电压逆相序期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电压逆相序期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压逆相序期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压逆相序期间C相正组合无功2电能增量"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "电流逆相序总次数，总累计时间" => [
            "03", "08", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "电流逆相序总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "电流逆相序记录" => [ //最近10次
            "03", "08", "00", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "电流逆相序期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电流逆相序期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流逆相序期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流逆相序期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电流逆相序期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电流逆相序期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流逆相序期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流逆相序期间A相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电流逆相序期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电流逆相序期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流逆相序期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流逆相序期间B相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电流逆相序期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电流逆相序期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流逆相序期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流逆相序期间C相正组合无功2电能增量"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "电压不平衡逆相序总次数，总累计时间" => [
            "03", "09", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "电压不平衡逆相序总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "电压不平衡逆相序记录" => [ //最近10次
            "03", "09", "00", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XX.XX", 2, "%", "double", "最大不平衡率"],
                ["XXXXXX.XX", 4, "kWh", "double", "电压不平衡逆相序期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电压不平衡逆相序期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压不平衡逆相序期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压不平衡逆相序期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电压不平衡逆相序期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电压不平衡逆相序期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压不平衡逆相序期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压不平衡逆相序期间A相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电压不平衡逆相序期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电压不平衡逆相序期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压不平衡逆相序期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压不平衡逆相序期间B相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电压不平衡逆相序期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电压不平衡逆相序期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压不平衡逆相序期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电压不平衡逆相序期间C相正组合无功2电能增量"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "电流不平衡逆相序总次数，总累计时间" => [
            "03", "0A", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "电流不平衡逆相序总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "电流不平衡逆相序记录" => [ //最近10次
            "03", "0A", "00", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XX.XX", 2, "%", "double", "最大不平衡率"],
                ["XXXXXX.XX", 4, "kWh", "double", "电流不平衡逆相序期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电流不平衡逆相序期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流不平衡逆相序期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流不平衡逆相序期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电流不平衡逆相序期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电流不平衡逆相序期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流不平衡逆相序期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流不平衡逆相序期间A相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电流不平衡逆相序期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电流不平衡逆相序期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流不平衡逆相序期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流不平衡逆相序期间B相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电流不平衡逆相序期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "电流不平衡逆相序期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流不平衡逆相序期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电流不平衡逆相序期间C相正组合无功2电能增量"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "ABC相失流总次数，总累计时间" => [
            "03", "0B", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "A相失流总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "B相失流总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "C相失流总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "A相失流记录" => [ //最近10次
            "03", "0B", "01", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "失流期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "失流期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失流期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失流期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "失流期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "失流期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失流期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失流期间A相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "失流期间A相电压"],
                ["XXX.XXX", 3, "A", "double", "失流期间A相电流"],
                ["XX.XXXX", 3, "kW", "double", "失流期间A相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "失流期间A相无功功率"],
                ["X.XXX", 2, "", "double", "失流期间A相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "失流期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "失流期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失流期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失流期间B相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "失流期间B相电压"],
                ["XXX.XXX", 3, "A", "double", "失流期间B相电流"],
                ["XX.XXXX", 3, "kW", "double", "失流期间B相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "失流期间B相无功功率"],
                ["X.XXX", 2, "", "double", "失流期间B相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "失流期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "失流期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失流期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "失流期间C相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "失流期间C相电压"],
                ["XXX.XXX", 3, "A", "double", "失流期间C相电流"],
                ["XX.XXXX", 3, "kW", "double", "失流期间C相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "失流期间C相无功功率"],
                ["X.XXX", 2, "", "double", "失流期间C相功率因数"],
            ],
            "r",
            "最近10次"
        ],
        "B相失流记录" => ["03", "0B", "02", "01", "引用[A相失流记录]格式", "r", "最近10次"], //最近10次
        "C相失流记录" => ["03", "0B", "03", "01", "引用[A相失流记录]格式", "r", "最近10次"], //最近10次
        //"---",
        "ABC相过流总次数，总累计时间" => [
            "03", "0C", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "A相过流总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "B相过流总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "C相过流总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "A相过流记录" => [ //最近10次
            "03", "0C", "01", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "过流期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过流期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过流期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过流期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "过流期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过流期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过流期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过流期间A相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "过流期间A相电压"],
                ["XXX.XXX", 3, "A", "double", "过流期间A相电流"],
                ["XX.XXXX", 3, "kW", "double", "过流期间A相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "过流期间A相无功功率"],
                ["X.XXX", 2, "", "double", "过流期间A相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "过流期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过流期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过流期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过流期间B相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "过流期间B相电压"],
                ["XXX.XXX", 3, "A", "double", "过流期间B相电流"],
                ["XX.XXXX", 3, "kW", "double", "过流期间B相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "过流期间B相无功功率"],
                ["X.XXX", 2, "", "double", "过流期间B相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "过流期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过流期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过流期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过流期间C相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "过流期间C相电压"],
                ["XXX.XXX", 3, "A", "double", "过流期间C相电流"],
                ["XX.XXXX", 3, "kW", "double", "过流期间C相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "过流期间C相无功功率"],
                ["X.XXX", 2, "", "double", "过流期间C相功率因数"],
            ],
            "r",
            "最近10次"
        ],
        "B相过流记录" => ["03", "0C", "02", "01", "引用[A相过流记录]格式", "r", "最近10次"], //最近10次
        "C相过流记录" => ["03", "0C", "03", "01", "引用[A相过流记录]格式", "r", "最近10次"], //最近10次
        //"---",
        "ABC相断流总次数，总累计时间" => [
            "03", "0D", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "A相断流总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "B相断流总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "C相断流总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "A相断流记录" => [ //最近10次
            "03", "0D", "01", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "断流期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "断流期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断流期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断流期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "断流期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "断流期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断流期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断流期间A相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "断流期间A相电压"],
                ["XXX.XXX", 3, "A", "double", "断流期间A相电流"],
                ["XX.XXXX", 3, "kW", "double", "断流期间A相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "断流期间A相无功功率"],
                ["X.XXX", 2, "", "double", "断流期间A相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "断流期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "断流期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断流期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断流期间B相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "断流期间B相电压"],
                ["XXX.XXX", 3, "A", "double", "断流期间B相电流"],
                ["XX.XXXX", 3, "kW", "double", "断流期间B相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "断流期间B相无功功率"],
                ["X.XXX", 2, "", "double", "断流期间B相功率因数"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "断流期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "断流期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断流期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "断流期间C相正组合无功2电能增量"],
                ["XXX.X", 2, "V", "double", "断流期间C相电压"],
                ["XXX.XXX", 3, "A", "double", "断流期间C相电流"],
                ["XX.XXXX", 3, "kW", "double", "断流期间C相有功功率"],
                ["XX.XXXX", 3, "kvar", "double", "断流期间C相无功功率"],
                ["X.XXX", 2, "", "double", "断流期间C相功率因数"],
            ],
            "r",
            "最近10次"
        ],
        "B相断流记录" => ["03", "0D", "02", "01", "引用[A相断流记录]格式", "r", "最近10次"], //最近10次
        "C相断流记录" => ["03", "0D", "03", "01", "引用[A相断流记录]格式", "r", "最近10次"], //最近10次
        //"---",
        "ABC相潮流反向总次数，总累计时间" => [
            "03", "0E", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "A相潮流反向总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "B相潮流反向总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "C相潮流反向总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "A相潮流反向记录" => [ //最近10次
            "03", "0E", "01", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "潮流反向期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "潮流反向期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "潮流反向期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "潮流反向期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "潮流反向期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "潮流反向期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "潮流反向期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "潮流反向期间A相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "潮流反向期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "潮流反向期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "潮流反向期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "潮流反向期间B相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "潮流反向期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "潮流反向期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "潮流反向期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "潮流反向期间C相正组合无功2电能增量"],
            ],
            "r",
            "最近10次"
        ],
        "B相潮流反向记录" => ["03", "0E", "02", "01", "引用[A相潮流反向记录]格式", "r", "最近10次"], //最近10次
        "C相潮流反向记录" => ["03", "0E", "03", "01", "引用[A相潮流反向记录]格式", "r", "最近10次"], //最近10次
        //"---",
        "ABC相过载总次数，总累计时间" => [
            "03", "0E", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "A相过载总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "B相过载总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
                ["XXXXXX", 3, "次", "int", "C相过载总次数"],
                ["XXXXXX", 3, "分", "int", "总累计时间"],
            ],
            "r"
        ],
        "A相过载记录" => [ //最近10次
            "03", "0F", "01", "01",
            [
                ["YYMMDDhhmmss", 6, "", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "过载期间正向有功总电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过载期间反向有功总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过载期间组合无功1总电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过载期间组合无功2总电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "过载期间A相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过载期间A相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过载期间A相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过载期间A相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "过载期间B相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过载期间B相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过载期间B相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过载期间B相正组合无功2电能增量"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "过载期间C相正向有功电能增量"],
                ["XXXXXX.XX", 4, "kWh", "double", "过载期间C相反向有功电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过载期间C相正组合无功1电能增量"],
                ["XXXXXX.XX", 4, "kvarh", "double", "过载期间C相正组合无功2电能增量"],
            ],
            "r",
            "最近10次"
        ],
        "B相过载记录" => ["03", "0F", "02", "01", "引用[A相过载记录]格式", "r", "最近10次"], //最近10次
        "C相过载记录" => ["03", "0F", "03", "01", "引用[A相过载记录]格式", "r", "最近10次"], //最近10次
        //"---",
        "电压合格率统计数据" => [ //最近12个月
            "03", "10", "00", "00",
            [
                ["XXXXXX", 3, "分", "int", "电压监测时间"],
                ["XXXX.XX", 3, "%", "double", "电压合格率"],
                ["XXXX.XX", 3, "%", "double", "电压超限率"],
                ["XXXXXX", 3, "分", "int", "电压超上限时间"],
                ["XXXXXX", 3, "分", "int", "电压超下限时间"],
                ["XXX.X", 2, "V", "double", "最高电压"],
                ["MMDDhhmm", 4, "", "date", "最高电压出现时间"],
                ["XXX.X", 2, "V", "double", "最低电压"],
                ["MMDDhhmm", 4, "", "date", "最低电压出现时间"],
            ],
            "r",
            "最近12月"
        ],
        //"---",
        "A相电压合格率统计数据" => [ //最近12个月
            "03", "10", "01", "00",
            [
                ["XXXXXX", 3, "分", "int", "电压监测时间"],
                ["XXXX.XX", 3, "%", "double", "电压合格率"],
                ["XXXX.XX", 3, "%", "double", "电压超限率"],
                ["XXXXXX", 3, "分", "int", "电压超上限时间"],
                ["XXXXXX", 3, "分", "int", "电压超下限时间"],
                ["XXX.X", 2, "V", "double", "最高电压"],
                ["MMDDhhmm", 4, "", "date", "最高电压出现时间"],
                ["XXX.X", 2, "V", "double", "最低电压"],
                ["MMDDhhmm", 4, "", "date", "最低电压出现时间"],
            ],
            "r",
            "最近12月"
        ],
        //"---",
        "B相电压合格率统计数据" => [ //最近12个月
            "03", "10", "02", "00",
            [
                ["XXXXXX", 3, "分", "int", "电压监测时间"],
                ["XXXX.XX", 3, "%", "double", "电压合格率"],
                ["XXXX.XX", 3, "%", "double", "电压超限率"],
                ["XXXXXX", 3, "分", "int", "电压超上限时间"],
                ["XXXXXX", 3, "分", "int", "电压超下限时间"],
                ["XXX.X", 2, "V", "double", "最高电压"],
                ["MMDDhhmm", 4, "", "date", "最高电压出现时间"],
                ["XXX.X", 2, "V", "double", "最低电压"],
                ["MMDDhhmm", 4, "", "date", "最低电压出现时间"],
            ],
            "r",
            "最近12月"
        ],
        //"---",
        "C相电压合格率统计数据" => [ //最近12个月
            "03", "10", "03", "00",
            [
                ["XXXXXX", 3, "分", "int", "电压监测时间"],
                ["XXXX.XX", 3, "%", "double", "电压合格率"],
                ["XXXX.XX", 3, "%", "double", "电压超限率"],
                ["XXXXXX", 3, "分", "int", "电压超上限时间"],
                ["XXXXXX", 3, "分", "int", "电压超下限时间"],
                ["XXX.X", 2, "V", "double", "最高电压"],
                ["MMDDhhmm", 4, "", "date", "最高电压出现时间"],
                ["XXX.X", 2, "V", "double", "最低电压"],
                ["MMDDhhmm", 4, "", "date", "最低电压出现时间"],
            ],
            "r",
            "最近12月"
        ],
        //"---",
        "掉电总次数" => ["03", "11", "00", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "掉电发生时刻，结束时刻" => [ //最近10次
            "03", "11", "00", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "掉电发生时刻"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "结束时刻"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "需量超限总次数" => [
            "03", "12", "00", "00",
            [
                ["XXXXXX", 3, "次", "int", "正向有功需量超限总次数"],
                ["XXXXXX", 3, "次", "int", "反向有功需量超限总次数"],
                ["XXXXXX", 3, "次", "int", "第一象限无功需量超限总次数"],
                ["XXXXXX", 3, "次", "int", "第二象限无功需量超限总次数"],
                ["XXXXXX", 3, "次", "int", "第三象限无功需量超限总次数"],
                ["XXXXXX", 3, "次", "int", "第四象限无功需量超限总次数"],
            ],
            "r"
        ],
        "正向有功需量超限记录" => [ //最近10次
            "03", "12", "01", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "结束时刻"],
                ["XX.XXXX", 3, "kvar", "double", "需量超限期间正向有功最大需量及发生时间"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "未知"], //这项暂不知道是什么
            ],
            "r",
            "最近10次"
        ],
        "反向有功需量超限记录" => [ //最近10次
            "03", "12", "02", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "结束时刻"],
                ["XX.XXXX", 3, "kvar", "double", "需量超限期间正向有功最大需量及发生时间"], //这项是否需要改为 反向有功
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "未知"], //这项暂不知道是什么
            ],
            "r",
            "最近10次"
        ],
        "第一象限无功需量超限记录" => [ //最近10次
            "03", "12", "03", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "结束时刻"],
                ["XX.XXXX", 3, "kvar", "double", "需量超限期间正向有功最大需量及发生时间"], //这项是否需要改为 第一象限无功
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "未知"], //这项暂不知道是什么
            ],
            "r",
            "最近10次"
        ],
        "第二象限无功需量超限记录" => [ //最近10次
            "03", "12", "04", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "结束时刻"],
                ["XX.XXXX", 3, "kvar", "double", "需量超限期间正向有功最大需量及发生时间"], //这项是否需要改为 第二象限无功
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "未知"], //这项暂不知道是什么
            ],
            "r",
            "最近10次"
        ],
        "第三象限无功需量超限记录" => [ //最近10次
            "03", "12", "05", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "结束时刻"],
                ["XX.XXXX", 3, "kvar", "double", "需量超限期间正向有功最大需量及发生时间"], //这项是否需要改为 第三象限无功
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "未知"], //这项暂不知道是什么
            ],
            "r",
            "最近10次"
        ],
        "第四象限无功需量超限记录" => [ //最近10次
            "03", "12", "06", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "结束时刻"],
                ["XX.XXXX", 3, "kvar", "double", "需量超限期间正向有功最大需量及发生时间"], //这项是否需要改为 第四象限无功
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "未知"], //这项暂不知道是什么
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "编程总次数" => ["03", "30", "00", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "编程记录" => [ //最近10次
            "03", "30", "00", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["XXXXXXXX", 4 * 10, "", "uknow", "编程的前10个数据标识码（不足补FFFFFFFFH）"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "电表清零总次数" => ["03", "30", "01", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "电表清零记录" => [ //最近10次
            "03", "30", "01", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["XXXXXX.XX", 4, "kWh", "double", "电表清零前正向有功总电能"],
                ["XXXXXX.XX", 4, "kWh", "double", "电表清零前反向有功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前第一象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前第二象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前第三象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前第四象限无功总电能"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电表清零前A相正向有功电能"],
                ["XXXXXX.XX", 4, "kWh", "double", "电表清零前A相反向有功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前A相第一象限无功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前A相第二象限无功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前A相第三象限无功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前A相第四象限无功电能"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电表清零前B相正向有功电能"],
                ["XXXXXX.XX", 4, "kWh", "double", "电表清零前B相反向有功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前B相第一象限无功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前B相第二象限无功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前B相第三象限无功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前B相第四象限无功电能"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "电表清零前C相正向有功电能"],
                ["XXXXXX.XX", 4, "kWh", "double", "电表清零前C相反向有功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前C相第一象限无功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前C相第二象限无功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前C相第三象限无功电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "电表清零前C相第四象限无功电能"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "需量清零总次数" => ["03", "30", "02", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "需量清零记录" => [ //最近10次
            "03", "30", "02", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["XX.XXXXXX", 4, "kWh", "double", "需量清零前正向有功总最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前正向有功总最大需量发生时间"],
                ["XX.XXXXXX", 4, "kWh", "double", "需量清零前反向有功总最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前反向有功总最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前第一象限无功总最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前第一象限无功总最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前第二象限无功总最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前第二象限无功总最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前第三象限无功总最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前第三象限无功总最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前第四象限无功总最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前第四象限无功总最大需量发生时间"],
                //"---",
                ["XX.XXXXXX", 4, "kWh", "double", "需量清零前A相正向有功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前A相正向有功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kWh", "double", "需量清零前A相反向有功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前A相反向有功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前A相第一象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前A相第一象限无功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前A相第二象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前A相第二象限无功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前A相第三象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前A相第三象限无功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前A相第四象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前A相第四象限无功最大需量发生时间"],
                //"---",
                ["XX.XXXXXX", 4, "kWh", "double", "需量清零前B相正向有功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前B相正向有功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kWh", "double", "需量清零前B相反向有功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前B相反向有功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前B相第一象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前B相第一象限无功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前B相第二象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前B相第二象限无功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前B相第三象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前B相第三象限无功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前B相第四象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前B相第四象限无功最大需量发生时间"],
                //"---",
                ["XX.XXXXXX", 4, "kWh", "double", "需量清零前C相正向有功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前C相正向有功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kWh", "double", "需量清零前C相反向有功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前C相反向有功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前C相第一象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前C相第一象限无功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前C相第二象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前C相第二象限无功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前C相第三象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前C相第三象限无功最大需量发生时间"],
                ["XX.XXXXXX", 4, "kvarh", "double", "需量清零前C相第四象限无功最大需量"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "需量清零前C相第四象限无功最大需量发生时间"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "事件清零总次数" => ["03", "30", "03", "00", ["XXXXXX", 3, "次", "int", "包括总清及分项清"], "r"],
        "事件清零记录" => [ //最近10次
            "03", "30", "03", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["XXXXXXXX", 4 * 10, "", "uknow", "事件清零数据标识码"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "校时总次数" => ["03", "30", "04", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "校时记录" => [ //最近10次
            "03", "30", "04", "01",
            [
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "校时前时间"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "校时后时间"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "时段表编程总次数" => ["03", "30", "05", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "时段表编程记录" => [ //最近10次
            "03", "30", "05", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["hhmm", 2, "", "time", "时段表编程前第一套第1日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第一套第1日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第一套第2日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第一套第2日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第一套第3日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第一套第3日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第一套第4日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第一套第4日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第一套第5日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第一套第5日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第一套第6日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第一套第6日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第一套第7日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第一套第7日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第一套第8日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第一套第8日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第二套第1日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第二套第1日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第二套第2日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第二套第2日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第二套第3日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第二套第3日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第二套第4日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第二套第4日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第二套第5日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第二套第5日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第二套第6日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第二套第6日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第二套第7日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第二套第7日时段表数据"],
                ["hhmm", 2, "", "time", "时段表编程前第二套第8日时段表数据"],
                ["NN", 1, "", "string", "时段表编程前第二套第8日时段表数据"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "时区表编程总次数" => ["03", "30", "06", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "时区表编程记录" => [ //最近10次
            "03", "30", "06", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["MMDD", 2, "", "date", "时区表编程前第一套第1日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第一套第1日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第一套第2日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第一套第2日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第一套第3日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第一套第3日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第一套第4日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第一套第4日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第一套第5日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第一套第5日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第一套第6日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第一套第6日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第一套第7日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第一套第7日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第一套第8日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第一套第8日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第二套第1日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第二套第1日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第二套第2日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第二套第2日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第二套第3日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第二套第3日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第二套第4日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第二套第4日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第二套第5日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第二套第5日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第二套第6日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第二套第6日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第二套第7日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第二套第7日时区数据"],
                ["MMDD", 2, "", "date", "时区表编程前第二套第8日时区数据"],
                ["NN", 1, "", "string", "时区表编程前第二套第8日时区数据"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "周休日编程总次数" => ["03", "30", "07", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "周休日编程记录" => [ //最近10次
            "03", "30", "07", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["XX", 1, "", "string", "string", "周休日编程前采用的日时段表号"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "节假日编程总次数" => ["03", "30", "08", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "节假日编程记录" => [ //最近10次
            "03", "30", "08", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["YYMMDD", 3, "", "date", "节假日编程前第1节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第1节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第2节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第2节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第3节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第3节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第4节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第4节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第5节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第5节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第6节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第6节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第7节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第7节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第8节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第8节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第9节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第9节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第10节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第10节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第11节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第11节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第12节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第12节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第13节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第13节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第14节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第14节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第15节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第15节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第16节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第16节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第17节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第17节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第18节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第18节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第19节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第19节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第20节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第20节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第21节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第21节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第22节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第22节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第23节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第23节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第24节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第24节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第25节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第25节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第26节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第26节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第27节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第27节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第28节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第28节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第29节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第29节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第30节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第30节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第31节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第31节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第32节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第32节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第33节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第33节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第34节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第34节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第35节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第35节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第36节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第36节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第37节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第37节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第38节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第38节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第39节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第39节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第40节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第40节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第41节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第41节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第42节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第42节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第43节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第43节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第44节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第44节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第45节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第45节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第46节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第46节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第47节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第47节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第48节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第48节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第49节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第49节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第50节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第50节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第51节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第51节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第52节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第52节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第53节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第53节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第54节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第54节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第55节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第55节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第56节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第56节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第57节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第57节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第58节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第58节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第59节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第59节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第60节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第60节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第61节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第61节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第62节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第62节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第63节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第63节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第64节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第64节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第65节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第65节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第66节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第66节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第67节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第67节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第68节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第68节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第69节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第69节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第70节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第70节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第71节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第71节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第72节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第72节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第73节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第73节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第74节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第74节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第75节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第75节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第76节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第76节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第77节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第77节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第78节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第78节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第79节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第79节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第80节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第80节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第81节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第81节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第82节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第82节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第83节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第83节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第84节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第84节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第85节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第85节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第86节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第86节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第87节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第87节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第88节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第88节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第89节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第89节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第90节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第90节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第91节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第91节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第92节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第92节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第93节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第93节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第94节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第94节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第95节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第95节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第96节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第96节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第97节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第97节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第98节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第98节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第99节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第99节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第100节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第100节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第101节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第101节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第102节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第102节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第103节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第103节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第104节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第104节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第105节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第105节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第106节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第106节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第107节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第107节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第108节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第108节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第109节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第109节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第110节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第110节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第111节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第111节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第112节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第112节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第113节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第113节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第114节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第114节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第115节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第115节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第116节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第116节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第117节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第117节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第118节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第118节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第119节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第119节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第120节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第120节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第121节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第121节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第122节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第122节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第123节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第123节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第124节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第124节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第125节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第125节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第126节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第126节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第127节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第127节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第128节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第128节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第129节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第129节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第130节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第130节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第131节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第131节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第132节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第132节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第133节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第133节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第134节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第134节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第135节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第135节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第136节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第136节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第137节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第137节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第138节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第138节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第139节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第139节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第140节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第140节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第141节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第141节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第142节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第142节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第143节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第143节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第144节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第144节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第145节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第145节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第146节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第146节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第147节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第147节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第148节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第148节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第149节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第149节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第150节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第150节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第151节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第151节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第152节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第152节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第153节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第153节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第154节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第154节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第155节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第155节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第156节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第156节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第157节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第157节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第158节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第158节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第159节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第159节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第160节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第160节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第161节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第161节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第162节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第162节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第163节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第163节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第164节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第164节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第165节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第165节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第166节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第166节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第167节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第167节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第168节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第168节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第169节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第169节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第170节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第170节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第171节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第171节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第172节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第172节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第173节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第173节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第174节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第174节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第175节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第175节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第176节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第176节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第177节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第177节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第178节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第178节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第179节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第179节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第180节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第180节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第181节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第181节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第182节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第182节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第183节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第183节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第184节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第184节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第185节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第185节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第186节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第186节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第187节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第187节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第188节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第188节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第189节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第189节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第190节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第190节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第191节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第191节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第192节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第192节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第193节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第193节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第194节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第194节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第195节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第195节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第196节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第196节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第197节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第197节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第198节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第198节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第199节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第199节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第200节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第200节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第201节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第201节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第202节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第202节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第203节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第203节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第204节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第204节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第205节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第205节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第206节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第206节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第207节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第207节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第208节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第208节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第209节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第209节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第210节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第210节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第211节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第211节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第212节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第212节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第213节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第213节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第214节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第214节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第215节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第215节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第216节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第216节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第217节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第217节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第218节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第218节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第219节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第219节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第220节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第220节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第221节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第221节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第222节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第222节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第223节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第223节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第224节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第224节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第225节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第225节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第226节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第226节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第227节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第227节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第228节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第228节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第229节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第229节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第230节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第230节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第231节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第231节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第232节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第232节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第233节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第233节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第234节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第234节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第235节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第235节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第236节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第236节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第237节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第237节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第238节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第238节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第239节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第239节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第240节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第240节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第241节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第241节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第242节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第242节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第243节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第243节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第244节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第244节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第245节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第245节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第246节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第246节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第247节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第247节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第248节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第248节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第249节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第249节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第250节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第250节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第251节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第251节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第252节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第252节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第253节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第253节假日数据"],
                ["YYMMDD", 3, "", "date", "节假日编程前第254节假日数据"],
                ["NN", 1, "", "string",  "节假日编程前第254节假日数据"],

            ],
            "r",
            "最近10次"
        ],
        //"---",
        "有功组合方式编程总次数" => ["03", "30", "09", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "有功组合方式编程记录" => [ //最近10次
            "03", "30", "09", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["XX", 1, "", "string", "有功组合方式编程前的有功组合方式特征字"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "无功组合方式1编程总次数" => ["03", "30", "0A", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "无功组合方式1编程记录" => [ //最近10次
            "03", "30", "0A", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["XX", 1, "", "string", "无功组合方式1编程前的有功组合方式特征字"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "无功组合方式2编程总次数" => ["03", "30", "0B", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "无功组合方式2编程记录" => [ //最近10次
            "03", "30", "0B", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["XX", 1, "", "string", "无功组合方式2编程前的有功组合方式特征字"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "结算日编程总次数" => ["03", "30", "0C", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "结算日编程记录" => [ //最近10次
            "03", "30", "0C", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["C0C1C2C3", 4, "", "uknow", "操作者代码"],
                ["DDhh", 2, "", "date", "结算日编程前每月第1结算日数据"],
                ["DDhh", 2, "", "date", "结算日编程前每月第2结算日数据"],
                ["DDhh", 2, "", "date", "结算日编程前每月第3结算日数据"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "开表盖总次数" => ["03", "30", "0D", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "开表盖记录" => [ //最近10次
            "03", "30", "0D", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "开表盖前正向有功总电能"],
                ["XXXXXX.XX", 4, "kWh", "double", "开表盖前反向有功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开表盖前第一象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开表盖前第二象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开表盖前第三象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开表盖前第四象限无功总电能"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "开表盖后正向有功总电能"],
                ["XXXXXX.XX", 4, "kWh", "double", "开表盖后反向有功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开表盖后第一象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开表盖后第二象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开表盖后第三象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开表盖后第四象限无功总电能"],
            ],
            "r",
            "最近10次"
        ],
        //"---",
        "开端钮盒总次数" => ["03", "30", "0E", "00", ["XXXXXX", 3, "次", "int"], "r"],
        "开端钮盒记录" => [ //最近10次
            "03", "30", "0E", "01",
            [
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "发生时刻"],
                ["YYMMDDhhmmss", 6, "年月日时分秒", "date", "结束时刻"],
                ["XXXXXX.XX", 4, "kWh", "double", "开端钮盒前正向有功总电能"],
                ["XXXXXX.XX", 4, "kWh", "double", "开端钮盒前反向有功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开端钮盒前第一象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开端钮盒前第二象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开端钮盒前第三象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开端钮盒前第四象限无功总电能"],
                //"---",
                ["XXXXXX.XX", 4, "kWh", "double", "开端钮盒后正向有功总电能"],
                ["XXXXXX.XX", 4, "kWh", "double", "开端钮盒后反向有功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开端钮盒后第一象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开端钮盒后第二象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开端钮盒后第三象限无功总电能"],
                ["XXXXXX.XX", 4, "kvarh", "double", "开端钮盒后第四象限无功总电能"],
            ],
            "r",
            "最近10次"
        ],
    ];
    const LAST_NO_DI0 = [
        "上1次" => "01",
        "上2次" => "02",
        "上3次" => "03",
        "上4次" => "04",
        "上5次" => "05",
        "上6次" => "06",
        "上7次" => "07",
        "上8次" => "08",
        "上9次" => "09",
        "上10次" => "0A",
    ];
    const LAST_MONTH_DI0 = [
        "本月" => "00",
        "上1月" => "01",
        "上2月" => "02",
        "上3月" => "03",
        "上4月" => "04",
        "上5月" => "05",
        "上6月" => "06",
        "上7月" => "07",
        "上8月" => "08",
        "上9月" => "09",
        "上10月" => "0A",
        "上11月" => "0B",
        "上12月" => "0C",
    ];
    const NOTES = [
        "注1" => "",
        "注2" => "",
        "注3" => "",
        "注4" => "",
        "注5" => "",
        "注6" => "",
    ];
    public function getData($name, $di0 = "")
    {
        if (!in_array($name, array_keys(self::DIs))) {
            return false;
        }
        $this->di = self::DIs[$name];
        if (is_string($this->di[4])) {
            $t = $this->getDisReference($this->di[4]);
            if (!$t || !self::DIs[$t][4]) {
                $this->errorMessage = "格式引用不存在";
                return false;
            }
            $this->di[4] = self::DIs[$t][4]; //格式引用
        }
        if (!strpos("r", $this->di[5]) === false) { //本项目不可读
            return false;
        }
        if (isset($this->di[6])) {
            if ($this->di[6] == '最近10次' && in_array($di0, array_keys(self::LAST_NO_DI0))) {
                $this->di[3] = self::LAST_NO_DI0[$di0];
            } elseif ($this->di[6] == '最近12月' && in_array($di0, array_keys(self::LAST_MONTH_DI0))) {
                $this->di[3] = self::LAST_MONTH_DI0[$di0];
            } else {
                $this->setError('1001', '请传入正确的历史参数');
                return false;
            }
        }
        $this->exec($name, '11', $this->di);
        if ($this->response->success) {
            if (is_array($this->di[4][0])) {
                return tool::caclResponses($this->di[4], $this->response->NData);
            } else {
                return tool::caclOneResponse($this->di[4], $this->response->NData);
            }
        }
        return false;
    }
}
